//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankService.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta
    {
        public int IdKarty { get; set; }
        public string NrKarty { get; set; }
        public string Kolor { get; set; }
        public string UrlGrafika { get; set; }
        public Nullable<bool> CzyAktywna { get; set; }
        public string Rodzaj { get; set; }
        public Nullable<int> IdOferta { get; set; }
    
        public virtual UslugaSzczegolowa UslugaSzczegolowa { get; set; }
    }
}
