//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankService.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lokata
    {
        public int IdLokata { get; set; }
        public string Oprocentowanie { get; set; }
        public Nullable<decimal> WkladPoczatkowy { get; set; }
        public Nullable<int> IdOferta { get; set; }
        public string Nazwa { get; set; }
    }
}
