//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankService.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacje
    {
        public int IdOperation { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> BeginingDate { get; set; }
        public Nullable<System.DateTime> FinishingDate { get; set; }
    }
}
