//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankService.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rachunek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rachunek()
        {
            this.Przelew = new HashSet<Przelew>();
        }
    
        public int IdRachunek { get; set; }
        public string NrRachunek { get; set; }
        public Nullable<decimal> StanRachunku { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public Nullable<int> IdOferta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przelew> Przelew { get; set; }
    }
}
