//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankService.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubezpieczenie
    {
        public int IdUbezpieczenie { get; set; }
        public Nullable<decimal> WartoscPolisy { get; set; }
        public string RodzajPolisy { get; set; }
        public Nullable<decimal> Skladka { get; set; }
        public Nullable<int> IdOferta { get; set; }
    
        public virtual UslugaSzczegolowa UslugaSzczegolowa { get; set; }
    }
}
