//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferForView", Namespace="http://schemas.datacontract.org/2004/07/BankService.ViewModel")]
    public partial class TransferForView : object
    {
        
        private int IdTransferField;
        
        private string KindField;
        
        private string NameField;
        
        private System.Nullable<decimal> SumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTransfer
        {
            get
            {
                return this.IdTransferField;
            }
            set
            {
                this.IdTransferField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kind
        {
            get
            {
                return this.KindField;
            }
            set
            {
                this.KindField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Sum
        {
            get
            {
                return this.SumField;
            }
            set
            {
                this.SumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermamentTransferForView", Namespace="http://schemas.datacontract.org/2004/07/BankService.ViewModel")]
    public partial class PermamentTransferForView : object
    {
        
        private string ForeignNumberField;
        
        private int IdPTField;
        
        private string KindField;
        
        private string NameField;
        
        private System.Nullable<decimal> SumField;
        
        private string TermField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ForeignNumber
        {
            get
            {
                return this.ForeignNumberField;
            }
            set
            {
                this.ForeignNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPT
        {
            get
            {
                return this.IdPTField;
            }
            set
            {
                this.IdPTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kind
        {
            get
            {
                return this.KindField;
            }
            set
            {
                this.KindField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Sum
        {
            get
            {
                return this.SumField;
            }
            set
            {
                this.SumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Term
        {
            get
            {
                return this.TermField;
            }
            set
            {
                this.TermField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfferForView", Namespace="http://schemas.datacontract.org/2004/07/BankService.ViewModel")]
    public partial class OfferForView : object
    {
        
        private System.Nullable<System.DateTime> BeginingDateField;
        
        private System.Nullable<System.DateTime> FinishDateField;
        
        private int IdAccountField;
        
        private int IdOfferField;
        
        private System.Nullable<bool> IsActiveField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BeginingDate
        {
            get
            {
                return this.BeginingDateField;
            }
            set
            {
                this.BeginingDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FinishDate
        {
            get
            {
                return this.FinishDateField;
            }
            set
            {
                this.FinishDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAccount
        {
            get
            {
                return this.IdAccountField;
            }
            set
            {
                this.IdAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdOffer
        {
            get
            {
                return this.IdOfferField;
            }
            set
            {
                this.IdOfferField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanForView", Namespace="http://schemas.datacontract.org/2004/07/BankService.ViewModel")]
    public partial class LoanForView : object
    {
        
        private int IdLoanField;
        
        private string PercentField;
        
        private System.Nullable<decimal> SumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLoan
        {
            get
            {
                return this.IdLoanField;
            }
            set
            {
                this.IdLoanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Percent
        {
            get
            {
                return this.PercentField;
            }
            set
            {
                this.PercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Sum
        {
            get
            {
                return this.SumField;
            }
            set
            {
                this.SumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsurenceForView", Namespace="http://schemas.datacontract.org/2004/07/BankService.ViewModel")]
    public partial class InsurenceForView : object
    {
        
        private int IdInsurenceField;
        
        private string KindField;
        
        private System.Nullable<decimal> PriceField;
        
        private System.Nullable<decimal> ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdInsurence
        {
            get
            {
                return this.IdInsurenceField;
            }
            set
            {
                this.IdInsurenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kind
        {
            get
            {
                return this.KindField;
            }
            set
            {
                this.KindField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepositForView", Namespace="http://schemas.datacontract.org/2004/07/BankService.ViewModel")]
    public partial class DepositForView : object
    {
        
        private int IdDepositField;
        
        private System.Nullable<decimal> InitialContributionField;
        
        private string PercentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDeposit
        {
            get
            {
                return this.IdDepositField;
            }
            set
            {
                this.IdDepositField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> InitialContribution
        {
            get
            {
                return this.InitialContributionField;
            }
            set
            {
                this.InitialContributionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Percent
        {
            get
            {
                return this.PercentField;
            }
            set
            {
                this.PercentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardForView", Namespace="http://schemas.datacontract.org/2004/07/BankService.ViewModel")]
    public partial class CardForView : object
    {
        
        private string CardNumberField;
        
        private string ColorField;
        
        private int IdCardField;
        
        private string KindField;
        
        private string UrlGraficField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color
        {
            get
            {
                return this.ColorField;
            }
            set
            {
                this.ColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCard
        {
            get
            {
                return this.IdCardField;
            }
            set
            {
                this.IdCardField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kind
        {
            get
            {
                return this.KindField;
            }
            set
            {
                this.KindField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlGrafic
        {
            get
            {
                return this.UrlGraficField;
            }
            set
            {
                this.UrlGraficField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountForView", Namespace="http://schemas.datacontract.org/2004/07/BankService.ViewModel")]
    public partial class AccountForView : object
    {
        
        private System.Nullable<decimal> AccountBalanceField;
        
        private string AccountNumberField;
        
        private int IdAccountField;
        
        private System.Nullable<int> IdOfferField;
        
        private System.Nullable<bool> IsActiveField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AccountBalance
        {
            get
            {
                return this.AccountBalanceField;
            }
            set
            {
                this.AccountBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAccount
        {
            get
            {
                return this.IdAccountField;
            }
            set
            {
                this.IdAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdOffer
        {
            get
            {
                return this.IdOfferField;
            }
            set
            {
                this.IdOfferField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankServiceReference.IBankService")]
    public interface IBankService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetTransferForView", ReplyAction="http://tempuri.org/IBankService/GetTransferForViewResponse")]
        BankServiceReference.GetTransferForViewResponse GetTransferForView(BankServiceReference.GetTransferForViewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetTransferForView", ReplyAction="http://tempuri.org/IBankService/GetTransferForViewResponse")]
        System.Threading.Tasks.Task<BankServiceReference.GetTransferForViewResponse> GetTransferForViewAsync(BankServiceReference.GetTransferForViewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetPTForViews", ReplyAction="http://tempuri.org/IBankService/GetPTForViewsResponse")]
        BankServiceReference.GetPTForViewsResponse GetPTForViews(BankServiceReference.GetPTForViewsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetPTForViews", ReplyAction="http://tempuri.org/IBankService/GetPTForViewsResponse")]
        System.Threading.Tasks.Task<BankServiceReference.GetPTForViewsResponse> GetPTForViewsAsync(BankServiceReference.GetPTForViewsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetOfferForViews", ReplyAction="http://tempuri.org/IBankService/GetOfferForViewsResponse")]
        BankServiceReference.GetOfferForViewsResponse GetOfferForViews(BankServiceReference.GetOfferForViewsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetOfferForViews", ReplyAction="http://tempuri.org/IBankService/GetOfferForViewsResponse")]
        System.Threading.Tasks.Task<BankServiceReference.GetOfferForViewsResponse> GetOfferForViewsAsync(BankServiceReference.GetOfferForViewsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetOfferByDate", ReplyAction="http://tempuri.org/IBankService/GetOfferByDateResponse")]
        BankServiceReference.GetOfferByDateResponse GetOfferByDate(BankServiceReference.GetOfferByDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetOfferByDate", ReplyAction="http://tempuri.org/IBankService/GetOfferByDateResponse")]
        System.Threading.Tasks.Task<BankServiceReference.GetOfferByDateResponse> GetOfferByDateAsync(BankServiceReference.GetOfferByDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetLoanForView", ReplyAction="http://tempuri.org/IBankService/GetLoanForViewResponse")]
        BankServiceReference.GetLoanForViewResponse GetLoanForView(BankServiceReference.GetLoanForViewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetLoanForView", ReplyAction="http://tempuri.org/IBankService/GetLoanForViewResponse")]
        System.Threading.Tasks.Task<BankServiceReference.GetLoanForViewResponse> GetLoanForViewAsync(BankServiceReference.GetLoanForViewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetInsurance", ReplyAction="http://tempuri.org/IBankService/GetInsuranceResponse")]
        BankServiceReference.GetInsuranceResponse GetInsurance(BankServiceReference.GetInsuranceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetInsurance", ReplyAction="http://tempuri.org/IBankService/GetInsuranceResponse")]
        System.Threading.Tasks.Task<BankServiceReference.GetInsuranceResponse> GetInsuranceAsync(BankServiceReference.GetInsuranceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetDeposit", ReplyAction="http://tempuri.org/IBankService/GetDepositResponse")]
        BankServiceReference.GetDepositResponse GetDeposit(BankServiceReference.GetDepositRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetDeposit", ReplyAction="http://tempuri.org/IBankService/GetDepositResponse")]
        System.Threading.Tasks.Task<BankServiceReference.GetDepositResponse> GetDepositAsync(BankServiceReference.GetDepositRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetCard", ReplyAction="http://tempuri.org/IBankService/GetCardResponse")]
        BankServiceReference.GetCardResponse GetCard(BankServiceReference.GetCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetCard", ReplyAction="http://tempuri.org/IBankService/GetCardResponse")]
        System.Threading.Tasks.Task<BankServiceReference.GetCardResponse> GetCardAsync(BankServiceReference.GetCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetAccount", ReplyAction="http://tempuri.org/IBankService/GetAccountResponse")]
        BankServiceReference.GetAccountResponse GetAccount(BankServiceReference.GetAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetAccount", ReplyAction="http://tempuri.org/IBankService/GetAccountResponse")]
        System.Threading.Tasks.Task<BankServiceReference.GetAccountResponse> GetAccountAsync(BankServiceReference.GetAccountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTransferForView", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTransferForViewRequest
    {
        
        public GetTransferForViewRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTransferForViewResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTransferForViewResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BankServiceReference.TransferForView> GetTransferForViewResult;
        
        public GetTransferForViewResponse()
        {
        }
        
        public GetTransferForViewResponse(System.Collections.Generic.List<BankServiceReference.TransferForView> GetTransferForViewResult)
        {
            this.GetTransferForViewResult = GetTransferForViewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPTForViews", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPTForViewsRequest
    {
        
        public GetPTForViewsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPTForViewsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPTForViewsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BankServiceReference.PermamentTransferForView> GetPTForViewsResult;
        
        public GetPTForViewsResponse()
        {
        }
        
        public GetPTForViewsResponse(System.Collections.Generic.List<BankServiceReference.PermamentTransferForView> GetPTForViewsResult)
        {
            this.GetPTForViewsResult = GetPTForViewsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOfferForViews", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOfferForViewsRequest
    {
        
        public GetOfferForViewsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOfferForViewsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOfferForViewsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BankServiceReference.OfferForView> GetOfferForViewsResult;
        
        public GetOfferForViewsResponse()
        {
        }
        
        public GetOfferForViewsResponse(System.Collections.Generic.List<BankServiceReference.OfferForView> GetOfferForViewsResult)
        {
            this.GetOfferForViewsResult = GetOfferForViewsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOfferByDate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOfferByDateRequest
    {
        
        public GetOfferByDateRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOfferByDateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOfferByDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BankServiceReference.OfferForView> GetOfferByDateResult;
        
        public GetOfferByDateResponse()
        {
        }
        
        public GetOfferByDateResponse(System.Collections.Generic.List<BankServiceReference.OfferForView> GetOfferByDateResult)
        {
            this.GetOfferByDateResult = GetOfferByDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLoanForView", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLoanForViewRequest
    {
        
        public GetLoanForViewRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLoanForViewResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLoanForViewResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BankServiceReference.LoanForView> GetLoanForViewResult;
        
        public GetLoanForViewResponse()
        {
        }
        
        public GetLoanForViewResponse(System.Collections.Generic.List<BankServiceReference.LoanForView> GetLoanForViewResult)
        {
            this.GetLoanForViewResult = GetLoanForViewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInsurance", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetInsuranceRequest
    {
        
        public GetInsuranceRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInsuranceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetInsuranceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BankServiceReference.InsurenceForView> GetInsuranceResult;
        
        public GetInsuranceResponse()
        {
        }
        
        public GetInsuranceResponse(System.Collections.Generic.List<BankServiceReference.InsurenceForView> GetInsuranceResult)
        {
            this.GetInsuranceResult = GetInsuranceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeposit", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDepositRequest
    {
        
        public GetDepositRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDepositResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDepositResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BankServiceReference.DepositForView> GetDepositResult;
        
        public GetDepositResponse()
        {
        }
        
        public GetDepositResponse(System.Collections.Generic.List<BankServiceReference.DepositForView> GetDepositResult)
        {
            this.GetDepositResult = GetDepositResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCard", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCardRequest
    {
        
        public GetCardRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCardResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BankServiceReference.CardForView> GetCardResult;
        
        public GetCardResponse()
        {
        }
        
        public GetCardResponse(System.Collections.Generic.List<BankServiceReference.CardForView> GetCardResult)
        {
            this.GetCardResult = GetCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAccountRequest
    {
        
        public GetAccountRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BankServiceReference.AccountForView> GetAccountResult;
        
        public GetAccountResponse()
        {
        }
        
        public GetAccountResponse(System.Collections.Generic.List<BankServiceReference.AccountForView> GetAccountResult)
        {
            this.GetAccountResult = GetAccountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IBankServiceChannel : BankServiceReference.IBankService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class BankServiceClient : System.ServiceModel.ClientBase<BankServiceReference.IBankService>, BankServiceReference.IBankService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BankServiceClient() : 
                base(BankServiceClient.GetDefaultBinding(), BankServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IBankService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(BankServiceClient.GetBindingForEndpoint(endpointConfiguration), BankServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BankServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BankServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public BankServiceReference.GetTransferForViewResponse GetTransferForView(BankServiceReference.GetTransferForViewRequest request)
        {
            return base.Channel.GetTransferForView(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceReference.GetTransferForViewResponse> GetTransferForViewAsync(BankServiceReference.GetTransferForViewRequest request)
        {
            return base.Channel.GetTransferForViewAsync(request);
        }
        
        public BankServiceReference.GetPTForViewsResponse GetPTForViews(BankServiceReference.GetPTForViewsRequest request)
        {
            return base.Channel.GetPTForViews(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceReference.GetPTForViewsResponse> GetPTForViewsAsync(BankServiceReference.GetPTForViewsRequest request)
        {
            return base.Channel.GetPTForViewsAsync(request);
        }
        
        public BankServiceReference.GetOfferForViewsResponse GetOfferForViews(BankServiceReference.GetOfferForViewsRequest request)
        {
            return base.Channel.GetOfferForViews(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceReference.GetOfferForViewsResponse> GetOfferForViewsAsync(BankServiceReference.GetOfferForViewsRequest request)
        {
            return base.Channel.GetOfferForViewsAsync(request);
        }
        
        public BankServiceReference.GetOfferByDateResponse GetOfferByDate(BankServiceReference.GetOfferByDateRequest request)
        {
            return base.Channel.GetOfferByDate(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceReference.GetOfferByDateResponse> GetOfferByDateAsync(BankServiceReference.GetOfferByDateRequest request)
        {
            return base.Channel.GetOfferByDateAsync(request);
        }
        
        public BankServiceReference.GetLoanForViewResponse GetLoanForView(BankServiceReference.GetLoanForViewRequest request)
        {
            return base.Channel.GetLoanForView(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceReference.GetLoanForViewResponse> GetLoanForViewAsync(BankServiceReference.GetLoanForViewRequest request)
        {
            return base.Channel.GetLoanForViewAsync(request);
        }
        
        public BankServiceReference.GetInsuranceResponse GetInsurance(BankServiceReference.GetInsuranceRequest request)
        {
            return base.Channel.GetInsurance(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceReference.GetInsuranceResponse> GetInsuranceAsync(BankServiceReference.GetInsuranceRequest request)
        {
            return base.Channel.GetInsuranceAsync(request);
        }
        
        public BankServiceReference.GetDepositResponse GetDeposit(BankServiceReference.GetDepositRequest request)
        {
            return base.Channel.GetDeposit(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceReference.GetDepositResponse> GetDepositAsync(BankServiceReference.GetDepositRequest request)
        {
            return base.Channel.GetDepositAsync(request);
        }
        
        public BankServiceReference.GetCardResponse GetCard(BankServiceReference.GetCardRequest request)
        {
            return base.Channel.GetCard(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceReference.GetCardResponse> GetCardAsync(BankServiceReference.GetCardRequest request)
        {
            return base.Channel.GetCardAsync(request);
        }
        
        public BankServiceReference.GetAccountResponse GetAccount(BankServiceReference.GetAccountRequest request)
        {
            return base.Channel.GetAccount(request);
        }
        
        public System.Threading.Tasks.Task<BankServiceReference.GetAccountResponse> GetAccountAsync(BankServiceReference.GetAccountRequest request)
        {
            return base.Channel.GetAccountAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBankService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBankService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64946/BankService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BankServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IBankService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BankServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IBankService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IBankService,
        }
    }
}
